######################################################################
# Automatically generated by qmake (3.1) Thu May 30 14:30:39 2019
######################################################################

TEMPLATE = subdirs

SUBDIRS += eleme_dispatch eleme_dispatch_gui
